#!/bin/bash -eu

build() {
  rm -rf dist/*

  esbuild src/main.ts --bundle --minify --sourcemap --copy-files --outfile=dist/dist/main.js
  cp public/* dist/
}

serve() {
  rm -rf dist/*

  esbuild src/main.ts --bundle --outfile=dist/main.js --watch --serve=4000 --servedir=.
  waiter --dev
}

format() {
  prettier --write .
}