#!/bin/bash -eu

trap clean 1 2 3 6 9

SRC="src/client/main.ts"
PUBLIC="public"
DIST="dist"

ESBUILD="esbuild $SRC --bundle"

setup() {
  bun install
}

format() {
  prettier --write .
}

build() {
  if [ -e "$DIST" ]; then
    echo >&2 "Error: Already built. Run \`clean\` first"
    echo >&2
    exit 1
  fi

  mkdir "$DIST"
  cp "$PUBLIC"/* "$DIST"/

  $ESBUILD --outdir="$DIST"
}

serve() {
  export DIST
  bun run src/server/main.ts
}

dev() {
  # We serve from `public` in dev mode, because
  # because otherwise the server has to be restarted
  # for static assets to be rebuilt.
  
  DIST="$PUBLIC" serve &
  $ESBUILD --watch --outdir="$PUBLIC"
}

clean() {
  p:clean_if_exists "$DIST"
  p:clean_if_exists "$PUBLIC"/main.js
}

p:clean_if_exists() {
  if [ -e "$1" ]; then
    rm -rf "$1"
  fi
}
